#signup  
POST http://localhost:8900/auth/customer HTTP/1.1
Content-Type: application/json

{
    "email": "devnica@gmail.com",
    "password": "Lamisma123*",
    "phoneNumber": "+502-78564545"
}

### signin
POST http://localhost:8900/auth/signin HTTP/1.1
Content-Type: application/json

{
    "email": "devnica@gmail.com",
    "password": "Lamisma123*"
}